FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Polls API

Polls is a simple API allowing consumers to view polls and vote in them.

## URL 1 [/rest/usuari/{id}]

### Peticio de dades de perfil [GET]

#### Cas de peticio correcta

Si vols probar un cas de peticio incorrecta canvia el codi de Response a 500.

+ Parameters
    + id (required, number, `0`)

+ Response 200 (application/json)

        {
                    "idUsuari": 1,
                    "nom": "Erik",
                    "cognom1": "Vergara",
                    "cognom2": "Supervia",
                    "nickname": "erik22",
                    "email": "erik@gmail.com",
                    "telefon": "123456789"
        }

### Modificacio de dades de perfil [PUT]

Si es vol fer el cas de peticio incorrecta canviar el result a false i posar un missatge d'error al response

+ Parameters
    + id (required, number, `0`)
    
+ Request

        {
                    "nom": "Erik",
                    "cognom1": "Supervia",
                    "cognom2": "Vergara",
                    "nickname": "erik23",
                    "email": "chuck@gmail.com",
                    "telefon": "123456789",
                    "contrasenya": "pepe"
        }

+ Response 200 (application/json)

        {
            "result": true,
            "response": ""
        }
        
## URL 2 [/usuari/xat]

### Xats oberts [GET]

+ Response 200 (application/json)
        
        [

          {
        
            "idXat": 0,
        
            "usuari1": {
            
              "idUser": 0,
        
              "nom": "Erik",
        
              "cognom1": "Norris",
        
              "cognom2": "Vergara",
        
              "nickname": "cobra",
        
              "email": "errik@gmail.com",
        
              "telefon": "123456789"
        
            },
        
            "usuari2": {
            
              "idUser": 1,
        
              "nom": "pepe",
        
              "cognom1": "Norris",
        
              "cognom2": "Vergara",
        
              "nickname": "pepe2",
        
              "email": "peep@gmail.com",
        
              "telefon": "123456789"
        
            },
        
            "ultimMissatge": {
        
              "idMissatge": 1,
        
              "contingutMissatge": "JAJA",
        
              "dataMissatge": "2017-03-30T22:35:07"
        
            }
        
          },
        
          {
        
            "idXat": 1,
        
            "usuari1": {
            
              "idUser": 0,
        
              "nom": "oscar",
        
              "cognom1": "Norris",
        
              "cognom2": "Vergara",
        
              "nickname": "Oscar",
        
              "email": "oscar@gmail.com",
        
              "telefon": "123456789"
        
            },
        
            "usuari2": {
            
              "idUser": 2,
        
              "nom": "carmen",
        
              "cognom1": "Norris",
        
              "cognom2": "Vergara",
        
              "nickname": "carmenn",
        
              "email": "carmen@gmail.com",
        
              "telefon": "123456789"
        
            },
        
            "ultimMissatge": {
        
              "idMissatge": 1,
        
              "contingutMissatge": "Adios",
        
              "dataMissatge": "2017-03-30T22:35:07"
        
            }
        
          }
        
        ]
        
## URL [/usuari/xat/{id}]
### Missatges[GET]

+ Parameters
    + id (required, number, `2`)
    
+ Response 200 (application/json)

        [
        {
            "idMissatge": 0,
            "contingutMissatge": "Hola",
            "dataMissatge": "2017-03-30T22:35:07",
            "usuari": 
            {
              "idUser": 2,
        
              "nom": "carmen",
        
              "cognom1": "Norris",
        
              "cognom2": "Vergara",
        
              "nickname": "Carmen",
        
              "email": "carmen@gmail.com",
        
              "telefon": "123456789",
        
              "contrasenya": "pepe"
            }
        },
        {
            "idMissatge": 1,
            "contingutMissatge": "Adios",
            "dataMissatge": "2017-03-30T22:35:07",
            "usuari": 
            {
              "idUser": 0,
        
              "nom": "oscar",
        
              "cognom1": "Norris",
        
              "cognom2": "Vergara",
        
              "nickname": "Oscar",
        
              "email": "Oscar@gmail.com",
        
              "telefon": "123456789",
        
              "contrasenya": "pepe"
            }
        }
        ]